version: "3.8"
services:
    duo-task:
    image: duo-db
    build: .
    ports:
      - target: 80
        published: 80
    depends_on:
      - chaperoo-service    
  duo-nginx: 
    image: nginx:alpine
    
  depends on:
  - flask-app
